# Generated by Django 5.0.2 on 2024-04-04 23:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mb_id', models.CharField(help_text='MusicBrainz ID', max_length=36, unique=True)),
                ('artist_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mb_id', models.CharField(help_text='MusicBrainz ID', max_length=36, unique=True)),
                ('album_name', models.CharField(max_length=100)),
                ('release_date', models.DateField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='recordbin.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mb_id', models.CharField(help_text='MusicBrainz ID', max_length=36, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='recordbin.album')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('followed_users', models.ManyToManyField(related_name='followers', to='recordbin.profile')),
                ('listened_album_ids', models.ManyToManyField(related_name='saved_by', to='recordbin.profile')),
                ('saved_artists', models.ManyToManyField(related_name='saved_by', to='recordbin.artist')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('saved_releases', models.ManyToManyField(related_name='saved_by', to='recordbin.release')),
            ],
        ),
    ]
