# Generated by Django 4.2.11 on 2024-04-15 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_rating_remove_profile_listened_album_ids_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
